env:
  browser: true
  es6: true
  jest: true
  node: true
settings:
  react:
    version: detect
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:jsx-a11y/recommended"
  - "prettier"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
  parser: "@babel/eslint-parser"
plugins:
  - react
  - jest
  - "jsx-a11y"
  - "react-hooks"
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - warn
